apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "registry.fullname" . }}-registry-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pv.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pv.storage }}